[mod.info]
setup.start = "SR1 Renderer start loading"
setup.use_time = "SR1 Renderer loading has used: {} second"

[sr1.ship]
xml.loading = "Loading XML file: {}"
xml.load_done = "XML file loaded"
xml.load_time = "XML file loading has used: {} second"
ship.load = "Loading ship: {}"
ship.load_time = "Ship loading has used: {} second"
ship.info = "Ship info:\n- Parts: {}\n- Weight: {}"
ship.render.done = "Ship render done"
ship.valid = "valid ship file: {}"
ship.invaild = "invaild ship file: {}"
save.start = "saveing ship: {}"
folder.invalid = "Invalid folder: {}"
