[package]
name = "difficult_rocket_rs"
version = "0.2.23"
edition = "2021"
license-file = '../../LICENSE'
authors = [
    "shenjackyuanjie <3695888@qq.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = 'difficult_rocket_rs'
crate-type = ["cdylib"]

[profile.dev.package.rapier2d-f64]
opt-level = 3

[profile.release]
strip = true
opt-level = "s"
# codegen-units = 1

[dependencies.quick-xml]
version = "0.31.0"
features = ["serialize"]

[dependencies.serde]
version = "1.0.190"
features = ["derive"]

[dependencies.xml-rs]
version = "0.8.19"

[dependencies.serde-xml-rs]
version = "0.6.0"

[dependencies.rapier2d-f64]
version = "0.17.2"
features = ["simd-stable"]

[dependencies.pyo3]
version = "0.20.0"
features = ["extension-module" , "macros"]
