[package]
name = "difficult_rocket_rs"
version = "0.3.1"
edition = "2021"
license-file = '../../LICENSE'
authors = ["shenjackyuanjie <3695888@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = 'difficult_rocket_rs'
crate-type = ["cdylib"]

#[profile.dev.package.rapier2d-f64]
#opt-level = 2

[profile.release]
lto = "fat"
# 舍弃恐慌信息以快速终止程序，而非展开调用栈。
# 请以开发模式编译程序以检查恐慌信息。
panic = "abort"
opt-level = 2

[dependencies]
fs-err = "2.11.0"

quick-xml = { version = "0.31.0", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }

nalgebra = "0.32.5"
rapier2d-f64 = { version = "0.18.0", features = ["simd-stable"] }
pyo3 = { version = "0.21.2", features = ["extension-module", "macros"] }

dict_derive = "0.5"
