language = "简体中文"
language_set_to = "语言已经设置为：简体中文"
language_available = "可用语言列表: {}"

[main]
env.version.python = "Python 版本: {}"
env.version.DR = "Difficult_Rocket 版本: {}"
env.version.DR_rs = "Difficult_Rocket_rs 版本: {}"
env.version.pyglet = "pyglet 版本: {}"
version.now_on = "困难火箭的运行 Python 环境为"
version.need3p = "困难火箭需要 Python3.0+ 的环境"
version.best38p = "困难火箭是在 Python {write_py_v} 的环境下编写的，目前正在运行在Python {py_v}的环境下，可能产生BUG"
lang.language = "简 体 中 文 (zh-cn)"
logger.language = "日志记录语言为："
logger.created = "日志处理器创建完成"
logger.mkdir = "logs/ 文件夹不存在，已经新建文件夹"
logger.main_done = "主日志处理器创建完成"
logger.logfile_name = "日志文件文件名："
logger.logfile_level = "日志文件记录级别："
logger.logfile_fmt = "日志文件记录格式："
logger.logfile_datefmt = "日志文件日期格式："
game_start.at = "游戏主线程开始于："

[mod]
list = "Mod 列表: "
find.finded = "找到 Mod: {}"
load.start = "开始加载路径 {} 下的 Mod"
load.use_time = "Mod 加载消耗时间: {} 秒"
load.done = "所有 Mod 加载完成"
load.loading = "正在加载 Mod: {}"
load.faild.error = "Mod 加载失败: {} 错误信息: {}"
load.faild.not_exist = "Mod 加载失败: {} mod 路径不存在"
load.faild.no_mod_class = "Mod 加载失败: {} 没有找到 Mod 类"
init.success = "mod id: {} 版本号: {}"
init.faild = "Mod 初始化失败: {} 错误信息: {}\n堆栈信息: {}"
init.use_time = "Mod 初始化消耗时间: {} 秒"
event.error = "Mod 事件 {} 发生错误 {} Mod: {}\n堆栈信息: {}"
unload.faild.not_find = "Mod 卸载失败: {} 没有找到 Mod"
unload.faild.error = "Mod 卸载失败: {} 错误信息: {}\n堆栈信息: {}"
unload.success = "Mod 卸载成功: {}"
reload.faild.not_find = "Mod 重载失败: {} 没有找到 Mod 原始路径，正在尝试重新查找 mod"
reload.success = "Mod 重载成功: {}"

[client]
setup.start = "客户端加载开始"
setup.use_time = "客户端载入花费: {} 秒"
setup.use_time_ns = "客户端载入花费: {} 纳秒"
config.save.start = "正在保存配置文件"
config.save.done = "配置文件保存完成"
load.font.start = "正在加载文件夹 {} 下的字体文件"
load.font.file = "正在加载字体文件: {}"
load.font.error = "字体加载失败: {}\n错误信息: {}"
load.font.use_time = "字体加载消耗时间: {} 秒"

[window]
setup.start = "游戏窗口加载开始"
setup.use_time = "游戏窗口加载消耗时间: {} 秒"
setup.use_time_ns = "游戏窗口载入消耗时间: {} 纳秒"
os.pid_is = "游戏窗口 PID: {} PPID: {}"
button.been_press = "按钮被按下，目前状态为："
mouse.press = "鼠标在 {} 被按下，按键为：{}"
mouse.release = "鼠标在 {} 释放，按键为：{}"
mouse.RIGHT = "右键"
mouse.LEFT = "左键"
mouse.MIDDLE = "中键"
key.press = "按键 {} | {} 被按下"
key.release = "按键 {} | {} 被释放"
text.input = "输入字符 \"{}\""
text.new_line = "换行"
text.motion = "光标移动 {}"
text.motion_select = "光标选择 {}"
libs.local = "正在使用本地 pyglet 库 版本为: {}"
libs.outer = "正在使用全局 pyglet 库 版本为: {}\n(可能会造成bug，因为本地库版本为2.0dev9)"
fonts.found = "在字体列表中找到以下字体库: {}"
fonts.load = "正在加载字体: {}"
game.stop_get = "从{}传入关闭指令,关闭游戏中"
game.stop = "游戏正在关闭,保存数据中···"
game.end = "游戏已经关闭"
command.text = "输入命令: {}"
message.text = "输入信息: {}"
command.mods.reload.no_mod_id = "没有指定 mod id"

[server]
setup.start = "服务端开始加载"
setup.use_time = "服务端加载消耗时间: {} 秒"
os.pid_is = "服务端 PID: {} PPID: {}"

[game]
input = "控制台"
window = "窗口"
command = "游戏内命令行"
require_DR_rs = "需要 DR_rs 模块"
