[book]
authors = ["shenjack"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Difficult-Rocket-docs"

[build]
build-dir = './book'
create-missing = false
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

# 默认 404 文件
[output.html]
input-404 = "404.md"
additional-css = ["./theme/pagetoc.css"]
additional-js  = ["./theme/pagetoc.js"]

# Git 相关配置
git-repository-url = "https://github.com/shenjackyuanjie/Difficult-Rocket"
git-branch = "main"

# 右上角的 "在 Github 内打开" 按钮
open-on-text = "Found a bug? [Edit this page on GitHub.]"

# 目录折叠
[output.html.fold]
enable = true
level = 0

# 最大搜索数量
[output.html.search]
limit-results = 15

# 允许打印
[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[rust]
edition = "2021"   # the default edition for code blocks

# 从本地运行一些东西拿到 markdown 里来
[preprocessor.cmdrun]

### 扩展部分

# 检查文档内链接
#[output.linkcheck]
#follow-web-links = false
#warning-policy = "ignore"
#exclude = [ "requirement-dev.txt" ]
#traverse-parent-directories = true

# 支持脚注 ( {{footnote: Or is it?}} )
[preprocessor.footnote]

# 添加右侧目录
[preprocessor.theme]
turn-off = true
pagetoc        = true
pagetoc-width            = "13%"
sidebar-width            = "300px"

# 在新页面中打开链接
[preprocessor.external-links]
