language = "English"
language_set_to = "Language set to: English"
language_available = "Available languages list: {}"

[main]
env.version.python = "Python version: {}"
env.version.DR = "Difficult_Rocket version: {}"
env.version.DR_rs = "Difficult_Rocket_rs version: {}"
env.version.pyglet = "pyglet version: {}"
version.now_on = "Difficult Rocket is running on Python Vision"
version.need3p = "Difficult Rocket depends on Python vision 3.0+"
version.best38p = "Difficult Rocket is writen in Python {write_py_v}, and now is running on Python {py_v} may cause BUG"
lang.language = "English (EN-US)"
logger.language = "Logging language is: "
logger.created = "Log handler created"
logger.mkdir = "logs/ folder not found, now created"
logger.main_done = "Main log handler created "
logger.logfile_name = "Log file name : "
logger.logfile_level = "Log file record level : "
logger.logfile_fmt = "Log file record format : "
logger.logfile_datefmt = "Log file date format : "
game_start.at = "Game MainThread start at: {}"

[mod]
list = "Mod list: "
find.finded = "Mod founded: {}"
load.start = "Loading Mod in path {}"
load.use_time = "Mod loading has used: {} second"
load.done = "All Mod loaded"
load.loading = "Loading Mod: {}"
load.faild.error = "Mod loading faild: {} error: {}"
load.faild.not_exist = "Mod loading faild: {} mod path not exist"
load.faild.no_mod_class = "Mod loading faild: {} no Mod class"
init.success = "mod id: {} version: {}"
init.faild = "Mod init faild: {} error: {}\nstack: {}"
init.use_time = "Mod init has used: {} second"
event.error = "Mod event {} error {} Mod: {}\nstack: {}"
unload.not_find = "Mod unload faild: {} no Mod found"
unload.faild = "Mod unload faild: {} error: {}\nstack: {}"
unload.success = "Mod unload success: {}"
reload.faild.not_find = "Mod reload faild: {} no Mod found, trying to find mod again"
reload.success = "Mod reload success: {}"

[client]
setup.start = "Client start loading"
setup.use_time = "Client loading has used: {} second"
setup.use_time_ns = "Client loading has used: {} nano second"
config.save.start = "Saving config……"
config.save.done = "Config saved"

[window]
setup.start = "Window start loading"
setup.use_time = "Window loading has used: {} second"
setup.use_time_ns = "Window loading has used: {} nano second"
os.pid_is = "Window's PID: {} PPID: {}"
button.been_press = "Button pressed, the current state of the button is: "
mouse.press = "mouse was click at {} button is: {}"
mouse.release = "mouse release at {} button is: {}"
mouse.RIGHT = "right button"
mouse.LEFT = "left button"
mouse.MIDDLE = "middle button"
key.press = "key {} | {} been press"
key.release = "key {} | {} been release"
text.input = "input text \"{}\""
text.new_line = "new line"
text.motion = "text move {}"
text.motion_select = "text select {}"
libs.local = "using local pyglet, version: {}"
libs.outer = "using global pyglet, version: {}\n(may cause bug)"
fonts.found = "found fonts in font lib: {}"
fonts.load = "loading fonts: {}"
game.stop_get = "Received closing commands from {}, game closing"
game.stop = "game closing, saving data……"
game.end = "game closed"
command.text = "input command: {}"
message.text = "input message: {}"
command.mods.reload.no_mod_id = "no mod id specified"

[server]
setup.start = "Server start loading"
setup.use_time = "Server loading has used: {} second"
os.pid_is = "Server PID: {} PPID: {}"

[game]
input = "console"
window = "window"
command = "in game commands"
require_DR_rs = "require DR_rs module"
